board_top_left:
   x: 67
   y: 137
   z: -26
   world: "jeopardyworld"
   horizontal: "-x"
   out_offset: -1

max_char_length: 50
max_question_lines: 5

hologram:
   player1:
      x: 62.000
      y: 134.500
      z: -36.500
   player2:
      x: 65.000
      y: 134.500
      z: -36.500
   player3:
      x: 68.000
      y: 134.500
      z: -36.500
   question:
      x: 65.0
      y: 135.75
      z: -31.5

buzzer:
   player1:
      x: 62
      y: 133
      z: -37
   player2:
      x: 65
      y: 133
      z: -37
   player3:
      x: 68
      y: 133
      z: -37

first_board:
   cat_1:
      Name: "Binding of Isaac"
      1:
         Question: "Isaac is based on this biblical character."
         Answer: "Isaac"
         Worth: 100
      2:
         Question: "This item is the only one that can appear after the item pool is exhausted."
         Answer: "Breakfast"
         Worth: 200
      3:
         Question: "This is the floor number on which you would fight Mom."
         Answer: "6"
         Worth: 300
      4:
         Question: "This is the number of Tarot cards available in the game."
         Answer: "22"
         Worth: 400
      5:
         Question: "These are my top 5 favourite items in the game (Name one)"
         Answer: "Dr Fetus, Ipecac, Polyphemus, D6, Mutant Spider"
         Worth: 500
   cat_2:
      Name: "Pokemon"
      1:
         Question: "This pokemon is based on a seal."
         Answer: "Seel"
         Worth: 100
      2:
         Question: "This generation of Pokemon games first featured the Johto region."
         Answer: "Generation 2 (Gold/Silver/Crystal)"
         Worth: 200
      3:
         Question: "This is the first pokemon Ash catches in the Pokemon series."
         Answer: "Caterpie"
         Worth: 300
      4:
         Question: "This pokemon had no weaknesses before the introduction of the fairy type in generation 6."
         Answer: "Spiritomb and Sableye"
         Worth: 400
      5:
         Question: "According to its Pokedex entry, people put this “Zen charm” Pokemon’s hot droppings in their clothes for warmth."
         Answer: "Darumaka"
         Worth: 500
   cat_3:
      Name: "Dungeons & Dragons"
      1:
         Question: "This gelatinous cube is a type of enemy in Dungeons and Dragons."
         Answer: "Gelatinous Cube"
         Worth: 100
      2:
         Question: "This class in D&D has an ability called 'Rage'"
         Answer: "Barbarian"
         Worth: 200
      3:
         Question: "This is the amount of dice used to play Dungeons and Dragons."
         Answer: "7"
         Worth: 300
      4:
         Question: "This is Dustin's D&D class in Stranger Things"
         Answer: "Bard"
         Worth: 400
      5:
         Question: "This creature chases the main characters through a maze in the 2022 D&D film."
         Answer: "Displacer Beast"
         Worth: 500
   cat_4:
      Name: "Bored Games"
      1:
         Question: "A chess board has this many squares."
         Answer: "64"
         Worth: 100
      2:
         Question: "Where would you end up in Monopoly if you rolled 3 double sixes from Go."
         Answer: "Jail"
         Worth: 200
      3:
         Question: "In this board game you play as a raccoon building a business tycoon."
         Answer: "Raccoon Tycoon"
         Worth: 300
      4:
         Question: "This letter in scrabble is worth 5 points."
         Answer: "K"
         Worth: 400
      5:
         Question: "This board game has the same name as a play by Agatha Christie."
         Answer: "Mousetrap"
         Worth: 500
   cat_5:
      Name: "Bowling"
      1:
         Question: "This country's flag features a white moon and star on a red background."
         Answer: "Turkey"
         Worth: 100
      2:
         Question: "This unions strike ended yesterday."
         Answer: "SAG AFTRA"
         Worth: 200
      3:
         Question: "The titular character of this film is also known as 'The dude'"
         Answer: "The Big Lebowski"
         Worth: 300
      4:
         Question: "This band had hits with '1985' and 'Girl All the Bad Guys Want'"
         Answer: "Bowling for Soup"
         Worth: 400
      5:
         Question: "This book includes a detailed story of a prince losing his virginity."
         Answer: "Spare"
         Worth: 500
   cat_6:
      Name: "Before and After"
      1:
         Question: "This Taylor Swift album is a tragic event that happened in September 2001."
         Answer: "1989/11"
         Worth: 100
      2:
         Question: "This creator of the atomic bomb is a champion in League of Legends."
         Answer: "Oppenheimerdinger"
         Worth: 200
      3:
         Question: "This Disney+ series about a Welsh football team is a musical by Lin Manuel Miranda."
         Answer: "Welcome to Wrexhamilton"
         Worth: 300
      4:
         Question: "This vodka is another word for children."
         Answer: "Smirnoffspring"
         Worth: 400
      5:
         Question: "This horror comedy about animatronics, features a cartoonist who kidnaps his own father."
         Answer: "Five Nights at Freddy Got Fingered"
         Worth: 500
second_board:
   cat_1:
      Name: "Connect 4"
      1:
         Question: "John, Paul, George, Ringo."
         Answer: "The Beatles"
         Worth: 200
      2:
         Question: "Whiskey, Tango, Echo, Golf."
         Answer: "NATO phonetic alphabet letters"
         Worth: 400
      3:
         Question: "Cheap Fucking Knockoff, Gramps, Fucking disappointment, The Only Man In The Sky."
         Answer: "Homelander's nicknames"
         Worth: 600
      4:
         Question: "Manhattan, Spa, Fiji, Efes."
         Answer: "Drinks named after places"
         Worth: 800
      5:
         Question: "Shamrock, Razzmatazz, Tickle Me Pink, Jazzberry Jam."
         Answer: "Crayola Colours"
         Worth: 1000
   cat_2:
      Name: "On This Day"
      1:
         Question: "China: June 4th 1989"
         Answer: "Nothing :)"
         Worth: 200
      2:
         Question: "Monarchs: September 8th 2022"
         Answer: "Lizzie kicked the bucket"
         Worth: 400
      3:
         Question: "Movies: July 21st 2023"
         Answer: "Barbenheimer day"
         Worth: 600
      4:
         Question: "Gaming: September 17th 2013"
         Answer: "GTA V Release"
         Worth: 800
      5:
         Question: "Youtube: 17th December 2020"
         Answer: "Doggomain uploaded 'Wilbur Soot - Your New Boyfriend (Noteblock Edition)"
         Worth: 1000
   cat_3:
      Name: "Urban Definitions"
      1:
         Question: "Although an incorrect tense of awake, a reference to how people should be aware in current affairs."
         Answer: "Woke"
         Worth: 200
      2:
         Question: "When you are in an extreme reckless mode, feeling very mischievous, and lack concern for the well being of others. Normally caused by consuming lots of alcohol."
         Answer: "Goblin Mode"
         Worth: 400
      3:
         Question: "THE NEW RIZZ KING, the number 1 college football prospect in the country."
         Answer: "Baby Gronk"
         Worth: 600
      4:
         Question: "A disease. A horde. A bacteria that is always spreading and is near impossible to purge."
         Answer: "Dream stan"
         Worth: 800
      5:
         Question: "A practice particular to engineering students at the University of Saskatchewan. Involves stunting, painting things red, and hanging cars from bridges."
         Answer: "Gooning"
         Worth: 1000
         daily_double: 1
   cat_4:
      Name: "Um Actually"
      1:
         Question: "The 2011 game Minecraft, is a singleplayer sandbox game where you can create a world in either Survival, Creative or hardcore mode."
         Answer: "Actually it has multiplayer"
         Worth: 200
      2:
         Question: "The DoggoMain SMP, began on the 9th of January 2021, and followed a very brief and incomplete storyline where I teamed up with Adam, who was scared of sheep. Later the server was rebranded for a small Christmas story."
         Answer: "Actually it was called the Doggo SMP"
         Worth: 400
      3:
         Question: "Lady Gaga's Pokerface:Po-po-po-poker face, fu-fu-fuck her face (mum-mum-mum-mah)Po-po-po-poker face, fu-fu-fuck her face (mum-mum-mum-mah)I want to roll with him, a hard pair we will beA little gambling is fun when you're with me (I love it)."
         Answer: "Actually she says 'wanna roll with him'"
         Worth: 600
      4:
         Question: "Hugh Campbell Jr, Billy Butchers 'Canary', falls in love with Annie April, a member of 'The Seven' who goes by the alias 'Starlight'. She was recruited into The Seven after an interview following Lamplighters retirement."
         Answer: "Actually Annie's name is Annie January"
         Worth: 800
      5:
         Question: "Scott Pilgrim, the bassist for Sex Bob-omb, develops a crush on a delivery girl for Amazon.com named Ramona Flowers. In order to date Ramona, Scott must first defeat her 'League of Evil Exes,' a group of six ex-boyfriends and one ex-girlfriend."
         Answer: "Actually Ramona works for Amazon.ca"
         Worth: 1000
   cat_5:
      Name: "Dungeons & Dragons"
      1:
         Question: "You play as a bullet in this rogue like dungeon crawler."
         Answer: "Enter the Gungeon"
         Worth: 200
      2:
         Question: "This actor played Smaug the dragon in The Hobbit."
         Answer: "Benedict Cumberbatch"
         Worth: 400
      3:
         Question: "This is the next year of the dragon."
         Answer: "2024"
         Worth: 600
      4:
         Question: "Piccolo from Dragon Ball Z is this race."
         Answer: "Namekian"
         Worth: 800
      5:
         Question: "Ansilvund, Volskygge and Yngvild are all examples of this."
         Answer: "Dungeons in Skyrim"
         Worth: 1000
   cat_6:
      Name: "Logic"
      1:
         Question: "Name a five headed dragon in Yu-Gi-Oh!"
         Answer: "Five-Headed Dragon"
         Worth: 200
      2:
         Question: "B is always true if A is true. If A is false, what do we know about B?"
         Answer: "Nothing"
         Worth: 400
      3:
         Question: "This 11 letter word is most commonly spelled incorrectly."
         Answer: "Incorrectly"
         Worth: 600
      4:
         Question: "This Greek philosopher, taught by Plato, first studied systematic logic."
         Answer: "Aristotle"
         Worth: 800
      5:
         Question: "This is the contrapositive of the statement 'If it is raining, I get wet’"
         Answer: "If I don't get wet, it's not raining"
         Worth: 1000
         
final:
   Question: "What is my favourite drink?"
   Category: "Food and Drink"
   Answer: "Hot Chocolate"