board_top_left:
   x: 67
   y: 137
   z: -26
   world: "jeopardyworld"
   horizontal: "-x"
   out_offset: -1

max_char_length: 45

hologram:
   player1:
      x: 62.000
      y: 134.500
      z: -36.500
      world: "jeopardyworld"
   player2:
      x: 65.000
      y: 134.500
      z: -36.500
      world: "jeopardyworld"
   player3:
      x: 68.000
      y: 134.500
      z: -36.500
      world: "jeopardyworld"
   question:
      x: 65.0
      y: 135.75
      z: -31.5
      world: "jeopardyworld"

buzzer:
   player1:
      x: 62
      y: 133
      z: -37
      world: "jeopardyworld"
   player2:
      x: 65
      y: 133
      z: -37
      world: "jeopardyworld"
   player3:
      x: 68
      y: 133
      z: -37
      world: "jeopardyworld"

first_board:
   cat_1:
      Name: "Weebs"
      1:
         Question: "This transformation from Dragon Ball Z makes a character 50x more powerful, and makes their hair blonde and spiky"
         Answer: "Super saiyan"
         Worth: 100
      2:
         Question: "The villain Dio Brando appears in this anime/manga series"
         Answer: "JoJo’s Bizarre Adventure"
         Worth: 200
      3:
         Question: "This is the highest selling manga series of all time"
         Answer: "One piece"
         Worth: 300
      4:
         Question: "These are the names of the three walls in Attack on Titan"
         Answer: "Sina, Rose and Maria"
         Worth: 400
      5:
         Question: "The servant Caster in Fate/Zero was inspired by this French nobleman"
         Answer: "Gilles de Rais"
         Worth: 500
   cat_2:
      Name: "Borders"
      1:
         Question: "This is the border of a circle"
         Answer: "Circumference"
         Worth: 100
      2:
         Question: "Handsome Jack is from this video game series "
         Answer: "Borderlands"
         Worth: 200
      3:
         Question: "These 2 countries share the longest total land border"
         Answer: "USA and Canada"
         Worth: 300
      4:
         Question: "This continent is home to a four nation quadripoint (technically 2 tripoints that are very close)"
         Answer: "Africa"
         Worth: 400
      5:
         Question: "These 2 countries share the longest continuous land border "
         Answer: "Russia and Kazakhstan"
         Worth: 500
   cat_3:
      Name: "How Do I Craft This Again?"
      1:
         Question: "This item is crafted using sand and gunpowder"
         Answer: "TNT"
         Worth: 100
      2:
         Question: "This item had its crafting recipe removed, and can now only be found in chests e.g. from ruined portals"
         Answer: "Enchanted Golden Apple"
         Worth: 200
      3:
         Question: "To craft the most filling food item in the game, the player must pick this flower"
         Answer: "Dandelion or Blue Orchid"
         Worth: 300
      4:
         Question: "These two items can be combined to craft granite"
         Answer: "Diorite and Nether Quartz"
         Worth: 400
      5:
         Question: "This block can be crafted using 81 of another block"
         Answer: "Blue ice"
         Worth: 500
   cat_4:
      Name: "Films"
      1:
         Question: "This is the director of the newest Spiderman trilogy"
         Answer: "Jon Watts"
         Worth: 100
      2:
         Question: "This film won Best Picture at the Oscars this year"
         Answer: "Nomadland"
         Worth: 200
      3:
         Question: "This is how many Sharknado films have been made"
         Answer: "6"
         Worth: 300
      4:
         Question: "What make of car is most commonly used by James Bond"
         Answer: "Aston Martin DB5"
         Worth: 400
      5:
         Question: "This country is where Jurassic Park is set"
         Answer: "Costa Rica"
         Worth: 500
   cat_5:
      Name: "Tech Support"
      1:
         Question: "Facebook recently changed its name to this word, meaning self-referential "
         Answer: "Meta"
         Worth: 100
      2:
         Question: "This type of volatile memory is used to store the data currently being used on a computer"
         Answer: "RAM"
         Worth: 200
      3:
         Question: "This is what NFT stands for"
         Answer: "Non-Fungible Token"
         Worth: 300
      4:
         Question: "This test is used to determine if a computer can successfully imitate a human being"
         Answer: "Turing test"
         Worth: 400
      5:
         Question: "This english mathematician is credited as being the first ever computer programmer"
         Answer: "Ada Lovelace"
         Worth: 500
   cat_6:
      Name: "YouTube Rewind"
      1:
         Question: "This twitch streamer moved to YouTube this year, and got banned within a week"
         Answer: "Ludwig"
         Worth: 100
      2:
         Question: "This YouTuber recreated Squid Game with a $456,000 prize pool"
         Answer: "Mr Beast"
         Worth: 200
      3:
         Question: "This is the most viewed video posted in 2021 (Not counting music videos)"
         Answer: "$456,000 Squid Game In Real Life!"
         Worth: 300
      4:
         Question: "This famous video from 16 years ago recently changed it's description to protest the removal of dislikes"
         Answer: "Me at the zoo"
         Worth: 400
      5:
         Question: "This is the most viewed premiere of 2021"
         Answer: "Butter - BTS"
         Worth: 500
second_board:
   cat_1:
      Name: "Before and After"
      1:
         Question: "This job based social media is an Asian country bordering Bangladesh"
         Answer: "LinkedIndonesia"
         Worth: 200
      2:
         Question: "This musical featuring a boy who says 'Please Sir, I want some more' is the city the beatles are from"
         Answer: "Oliverpool"
         Worth: 400
      3:
         Question: "This batman villain is the second entry in the Pokedex"
         Answer: "Poison Ivysaur"
         Worth: 600
      4:
         Question: "This term for a lack of harmony is a Rex Orange County song"
         Answer: "Discorduroy Dreams"
         Worth: 800
      5:
         Question: "This franchise featuring an armless protagonist is a 2013 DC film"
         Answer: "Rayman Of Steel"
         Worth: 1000
   cat_2:
      Name: "Christmas Cracker"
      1:
         Question: "This person is the motherfuckin' president"
         Answer: "Joe Byron"
         Worth: 200
      2:
         Question: "This actress is known for playing characters that shouldn't be white"
         Answer: "Scarlett Johansson"
         Worth: 400
      3:
         Question: "Contrary to popular belief, this disney star turned pop singer is actually white"
         Answer: "Ariana Grande"
         Worth: 600
      4:
         Question: "This film featured RDJ not being white"
         Answer: "Tropic Thunder"
         Worth: 800
      5:
         Question: "This person tweeted 'Never eatin, only tweetin'"
         Answer: "Adamanatite"
         Worth: 1000
   cat_3:
      Name: "Geopolitical"
      1:
         Question: "This country recently tweeted a meme in response to threats of war "
         Answer: "Ukraine"
         Worth: 200
      2:
         Question: "People campaigned for this country to be free after a long-standing conflict reignited with its neighbour"
         Answer: "Palestine"
         Worth: 400
      3:
         Question: "This country recently changed its flags colour as an ode to its revolution"
         Answer: "France"
         Worth: 600
      4:
         Question: "This Latin American country recently had the largest landslide in an election in history"
         Answer: "Chile"
         Worth: 800
      5:
         Question: "This country’s military seized power in February after a successful coup"
         Answer: "Myanmar"
         Worth: 1000
   cat_4:
      Name: "On Christmas Day"
      1:
         Question: "This event happened in 1914"
         Answer: "Christmas Day Truce "
         Worth: 200
      2:
         Question: "This fella was born between 6 and 4 BC"
         Answer: "Jesus"
         Worth: 400
      3:
         Question: "This famous scientist who defined the laws of motion was born in 1642"
         Answer: "Isaac Newton"
         Worth: 600
      4:
         Question: "This actor known for his moustache died in 1977"
         Answer: "Charlie Chaplin"
         Worth: 800
      5:
         Question: "This former president of the Soviet Union resigned in 1991"
         Answer: "Mikhail Gorbachev"
         Worth: 1000
   cat_5:
      Name: "Red and Green"
      1:
         Question: "This country singer released their fourth studio album, 'Red', in 2012"
         Answer: "Taylor Swift"
         Worth: 200
      2:
         Question: "‘Green light’ is a song by this New Zealand artist"
         Answer: "Lorde"
         Worth: 400
      3:
         Question: "This is a song about a car by Prince"
         Answer: "Little Red Corvette"
         Worth: 600
      4:
         Question: "This green mineral can be mined in Skyrim"
         Answer: "Malachite"
         Worth: 800
      5:
         Question: "This scientific theory states that red and green hues are perceived by the same receptor complexes in our eyes"
         Answer: "Opponent-process theory"
         Worth: 1000
   cat_6:
      Name: "Compounded"
      1:
         Question: "The act of 'finishing' and the Hasan word"
         Answer: "Nutcracker"
         Worth: 200
      2:
         Question: "A film based on a fanfiction about Harry Styles and Cool____Games.com"
         Answer: "aftermath"
         Worth: 400
      3:
         Question: "There are 7 of these in the world and JSchlatt likes these"
         Answer: "Seamen"
         Worth: 600
         daily_double: 1
      4:
         Question: "Advanced RISC Machines and something that could be styled as a 'Chesterfield', 'Bergere' or 'Windsor'"
         Answer: "armchair"
         Worth: 800
      5:
         Question: "The back part of something and home on the _____"
         Answer: "Rearrange"
         Worth: 1000
         
final:
   Question: "What is my favourite drink?"
   Answer: "Hot Chocolate"