board_top_left:
   x: 67
   y: 137
   z: -26
   world: "jeopardyworld"
   horizontal: "-x"
   out_offset: -1
   cover_offset: 3

max_char_length: 60
max_question_lines: 5

hologram:
   player1:
      x: 62.000
      y: 134.500
      z: -36.500
   player2:
      x: 65.000
      y: 134.500
      z: -36.500
   player3:
      x: 68.000
      y: 134.500
      z: -36.500
   question:
      x: 65.0
      y: 136.75
      z: -31.5

buzzer:
   player1:
      x: 62
      y: 133
      z: -37
   player2:
      x: 65
      y: 133
      z: -37
   player3:
      x: 68
      y: 133
      z: -37

first_board:
   cat_1:
      Name: "Chess"
      1:
         Question: "This rule was made by the French (ew)"
         Answer: "En Passant"
         Worth: 100
      2:
         Question: "This is the name of the chess player Beth Harmon defeats in her bid for world champion."
         Answer: "Vasily Borgov"
         Worth: 200
      3:
         Question: "Remy LeBeau is a Marvel superhero commonly known by this chess term."
         Answer: "Gambit"
         Worth: 300
      4:
         Question: "This is the current chess world champion."
         Answer: "Ding Liren"
         Worth: 400
      5:
         Question: "The Seventh Seal, is a 1957 chess film by Ingmar Bergman from this country."
         Answer: "Sweden"
         Worth: 500
   cat_2:
      Name: "Vocaloid"
      1:
         Question: "This Japanese company produced Vocaloid"
         Answer: "Yamaha"
         Worth: 100
      2:
         Question: "Akihiko Kondo married this character in 2018."
         Answer: "Hatsune Miku"
         Worth: 200
      3:
         Question: "This is the original voice actor of Hatsune Miku"
         Answer: "Saki Fujita"
         Worth: 300
      4:
         Question: "This is the age of Hatsune Miku"
         Answer: "16"
         Worth: 400
      5:
         Question: "This is the successor to the Vocaloid software."
         Answer: "Vocaloid 2"
         Worth: 500
   cat_3:
      Name: "Dinosaurs"
      1:
         Question: "This animated film series about dinosaurs, got a TV adaptation in 2007."
         Answer: "Land Before Time"
         Worth: 100
      2:
         Question: "This is the unofficial name of the T-rex from Jurassic Park, 1000 points for the actual name of it."
         Answer: "Rexy, Roberta"
         Worth: 200
      3:
         Question: "Canonically, this was the company that made Rex in Toy Story"
         Answer: "Mattel"
         Worth: 300
      4:
         Question: "This is the name of the fictional island on which Jurassic Park is built."
         Answer: "Isla Nublar"
         Worth: 400
      5:
         Question: "Arlo from The Good Dinosaur is this species of dinosaur."
         Answer: "Apatosaurus"
         Worth: 500
   cat_4:
      Name: "Spies"
      1:
         Question: "This is the voice actor for the main character in Spies in Disguise (2019)"
         Answer: "Tom Holland, Will Smith"
         Worth: 100
      2:
         Question: "Armie Hammer and Henry Cavill star alongside each other in this Guy Ritchie spy film."
         Answer: "The Man from U.N.C.L.E."
         Worth: 200
      3:
         Question: "This is the name of the first James Bond film."
         Answer: "Dr. No"
         Worth: 300
      4:
         Question: "This is the full name of MI6. (2 Answers)"
         Answer: "Secret Intelligence Service, Military Intelligence, Section 6"
         Worth: 400
      5:
         Question: "The Evidenzbureau is the oldest intelligence service in the world, founded in this European country in 1850."
         Answer: "Austria"
         Worth: 500
   cat_5:
      Name: "Mud in me"
      1:
         Question: "This is a soft, sticky matter resulting from the mixing of earth and water."
         Answer: "Mud"
         Worth: 100
      2:
         Question: "Many ships and planes have disappeared over this triangle in the ocean."
         Answer: "Bermuda Triangle"
         Worth: 200
      3:
         Question: "This crushing tool is essential in a bartenders kit."
         Answer: "Muddler"
         Worth: 300
      4:
         Question: "This goby (fish) with its eyes on raised bumps on top of its head is found in Mangrove swamps."
         Answer: "Mudskipper"
         Worth: 400
      5:
         Question: "This is a bad-tempered person, especially an old one."
         Answer: "Curmudgeon"
         Worth: 500
   cat_6:
      Name: "Toy Stories"
      1:
         Question: "This is the company behind the Barbie doll."
         Answer: "Mattel"
         Worth: 100
      2:
         Question: "This is one of the first toys inducted into the toy hall of fame in 1998. (11 answers)"
         Answer: "Barbie, Crayola crayons, Erector Set, Etch A Sketch, Frisbee, LEGO, marbles, Monopoly, Play-Doh, the teddy bear, and Tinkertoy"
         Worth: 200
      3:
         Question: "This is the name of the Toys 'R' Us giraffe."
         Answer: "Geoffrey"
         Worth: 300
      4:
         Question: "Mathilde's Dou Dou bunny is a pink knitted rabbit from this recent spy film."
         Answer: "No Time To Die"
         Worth: 400
      5:
         Question: "This is the name of the antagonistic 1950s doll from Toy Story 4."
         Answer: "Gabby Gabby"
         Worth: 500
second_board:
   cat_1:
      Name: "Before and After"
      1:
         Question: "This vocaloid is an animated martial arts film from 2008."
         Answer: "Hatsune Mikung Fu Panda"
         Worth: 200
      2:
         Question: "This poker-based roguelite is an iconic ragecomic face still used today."
         Answer: "Balatroll face"
         Worth: 400
      3:
         Question: "This chess piece is a sheet of fabric used to cover a doorway from outside elements."
         Answer: "Pawning"
         Worth: 600
      4:
         Question: "This dragon type pokemon starred in High School Musical."
         Answer: "Rayquazac Efron"
         Worth: 800
      5:
         Question: "This primordial life form from Marvels dark dimension is a 2012 film starring Matthew Mcconaughey as the titular character."
         Answer: "Dormammud"
         Worth: 1000
   cat_2:
      Name: "A little Fruity"
      1:
         Question: "Nuts are fruit. True or False?"
         Answer: "True"
         Worth: 200
      2:
         Question: "This attempted actor from stranger things recently thought 'zionism is sexy'"
         Answer: "Noah Schnapp"
         Worth: 400
      3:
         Question: "This fruit was iconically devoured by Denethor."
         Answer: "Tomato"
         Worth: 600
      4:
         Question: "This Veggietales character is actually a fruit."
         Answer: "Bob"
         Worth: 800
      5:
         Question: "Dakota Johnson has this fruit all around her house, while being allergic to them."
         Answer: "Limes"
         Worth: 1000
   cat_3:
      Name: "Names the sames"
      1:
         Question: "Garfield voice actor, NYC university"
         Answer: "Pratt"
         Worth: 200
      2:
         Question: "One of the Baudelaire orphans, One of the children in Charlie and The Chocolate Factory"
         Answer: "Violet"
         Worth: 400
      3:
         Question: "Catwoman, Shakespeare's wife"
         Answer: "Anne Hathaway"
         Worth: 600
      4:
         Question: "Hank Pymm, The Vulture"
         Answer: "Michael Douglas"
         Worth: 800
      5:
         Question: "Scottish actor in Succession, Physicist and musician"
         Answer: "Brian Cox"
         Worth: 1000
   cat_4:
      Name: "Geoguessr"
      1:
         Question: "In this country you can go any speed on the autobahn and visit the Brandenburg Gate."
         Answer: "Germany"
         Worth: 200
      2:
         Question: "In this country you can venture through the Amazon rainforest and climb Machu Picchu."
         Answer: "Peru"
         Worth: 400
      3:
         Question: "In this city you can stay at The Venetian and visit the Neon Museum."
         Answer: "Las Vegas"
         Worth: 600
      4:
         Question: "In this hotel chain you can safely stay in exchange for tokens, unless excommunicated."
         Answer: "The Continental"
         Worth: 800
      5:
         Question: "In this 'impenetrable city' you can visit the crystal catacombs."
         Answer: "Ba Sing Se"
         Worth: 1000
   cat_5:
      Name: "Films in a sentence"
      1:
         Question: "Who you gonna call?"
         Answer: "Ghostbusters"
         Worth: 200
      2:
         Question: "They were 7... and they fought like 700."
         Answer: "The Magnificent Seven"
         Worth: 400
      3:
         Question: "Escape or die frying."
         Answer: "Chicken Run"
         Worth: 600
      4:
         Question: "Check-in. Relax. Take a shower."
         Answer: "Psycho"
         Worth: 800
      5:
         Question: "Unwittingly he trained a dolphin to kill the President of the United States."
         Answer: "Day of the Dolphin"
         Worth: 1000
   cat_6:
      Name: "Terminology 101"
      1:
         Question: "Unlucky for some is the name for this number in bingo"
         Answer: "13"
         Worth: 200
      2:
         Question: "Czar, Shah and Sultan are all terms for this type of person."
         Answer: "Ruler"
         Worth: 400
      3:
         Question: "Albatross and mulligan are both terms used in this sport."
         Answer: "Golf"
         Worth: 600
         daily_double: 1
      4:
         Question: "This is the highest scoring hand type you can have in Texas Hold 'Em Poker."
         Answer: "Straight Flush"
         Worth: 800
      5:
         Question: "Ballerina is the term for rolling double of this number on dice."
         Answer: "2"
         Worth: 1000
         
final:
   Category: "Todays Game"
   Question: "This is the total sum of every number mentioned in this quiz excluding point values. (Closest wins)"
   Answer: "18,689"