name: Jeopardy
version: 0.2
author: Adamm
main: me.adamm.updatedjeopardy.Main
description: A plugin for the jeopardy gameshow in Minecraft!
api-version: 1.20
depend: [DecentHolograms]
commands:
   jactivate:
      description: Activates the buzzers
   janswer:
      description: Validates an answer to a question
   jask:
      description: Asks a question
   jbet:
      description: Adds a bet to the daily double
   jload:
      description: Loads a jeopardy board from the config
   jplayer:
      description: Adds and removes players from the game
   jreveal:
      description: Reveals an answer
   jreset:
      description: Resets the game
   jfinal:
      description: Command for the final jeopardy
   jadd:
      description: Command for adding points to a player
   jset:
      description: Command for setting points of a player
   jremove:
      description: Command for removing points from a player
   jskip:
      description: Command for skipping an active question
   jsaveimage:
      description: Command for saving an image template for the image board
   jloadimage:
      description: Command for loading an image template on image board
   jhelp:
      description: Command for displaying the help text
   vanish:
      description: Command for making a player appear or disappear
      aliases: [v]
permissions:
   jeopardy.gamemaster:
      description: Permission for the host / game master of the jeopardy game
      default: op
      children:
         jeopardy.activatebuzzers: true
         jeopardy.answerquestions: true
         jeopardy.revealanswer: true
   jeopardy.gameadmin:
      description: Permission for game admins of the jeopardy game
      default: op
      children:
         jeopardy.editscores: true
         jeopardy.askquestions: true
         jeopardy.startfinal: true
         jeopardy.adminhelp: true
         jeopardy.loadboard: true
         jeopardy.loadimage: true
         jeopardy.editplayers: true
         jeopardy.saveimage: true
         jeopardy.resetgame: true
         jeopardy.skipquestion: true
   jeopardy.vanish:
      description: Permissions for players to toggle their visibility
      default: op
      
         